owncloud/user_management

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/WebUIUsersContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/UserPageElement/GroupList.php
tests/acceptance/features/lib/UsersPage.php
tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
tests/acceptance/features/webUIManageUsersGroups/addGroup.feature
tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature
tests/acceptance/features/webUIManageUsersGroups/manageUsers.feature

Add tests/acceptance folder, containing the ``webUIManageQuota`` and ``webUIManageUsersGroups`` test suites that used to be in ``core`` ``master``.
Put together the various infrastructure needed - ``behat.yml`` and so on.
Note: ``login.feature`` was in ``webUIManageUsersGroups`` - it is being left in ``core`` because it is not a UI user management feature, it belongs in ``core``. See https://github.com/owncloud/core/pull/30874

Add UI acceptance tests for User Management

---

appinfo/info.xml

When a group admin is logged in users
page should be accessible.

Add users page for group-admin user

---

.drone.yml

To check if the build fails during nightly runs - we need to check the build status on the latest push.
Additionally it is good to know, if any push on the release branches results in a failure

notify of failures when pushes occur on master/release branch

---

tests/acceptance/config/behat.yml

1) Remove mailhogUrl from behat.yml - was removed in core
and likely also needs changes to fix testing on the webUI with a group called "a/slash"

Remove mailhogUrl from behat.yml - was removed in core

---

lib/Controller/UsersController.php

Fix the missing asterisk in the php-doc.
Without the asterisk it might affect the
annotation parseing.

Fix missing asterisk in the php-doc

---

js/groups.js
tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature

fixes https://github.com/owncloud/user_management/issues/19
Text added by phil-davis:
Also see core issue https://github.com/owncloud/core/issues/31279 - groups with ``/`` or ``%`` in the name do not list the members
These problems are here in the ``user_management`` app, and also in ``core`` ``stable10`` (which still has this user management code bundled in core)

do not urlencode group id

---

tests/acceptance/features/bootstrap/WebUIUsersContext.php

If, for example, the quota test fails, then it throws an exception which spews out a long stack trace. That looks ugly and makes it seem like there is something wrong with the Behat code. I am not sure why we coded those exceptions?
Replace with ``PHPUnit_Framework_Assert::assert*`` calls. Those produce a much friendlier-looking failure output.

Replace throw exception with assert in acceptance tests

---

tests/acceptance/features/bootstrap/WebUIUsersContext.php
tests/acceptance/features/lib/DisabledUserPage.php
tests/acceptance/features/lib/UsersPage.php
tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature

Forward port from core ``stable10``
Supersedes #25 
The 2nd commit just formats white space in ``deleteUsers.feature`` so it matches core ``stable10`` (this is a convenient place to also fixup this small difference)
The 3rd commit skips the test scenario, because it currently fails here in user_management - see issue #24 
4th commit - Make delete user acceptance test text consistent with disable user
5th commit - Fixup addUsers feature description

UI test for disable user

---

.drone.yml

After core https://github.com/owncloud/core/pull/31348 it is possible to run webUI acceptance tests from the common ``tests/acceptance/run.sh`` script, so do it.

Use acceptance test run.sh for webUI tests

---

.drone.yml

``.drone.yml`` in this repo was using ``GIT_REFERENCE`` in the ``install-server`` section. That has started failing.
Actually I do not know why it is different to other app ```.drone.yml`` that use ```version`` and specify a tarball like ``daily-master-qa`` or ``daily-stable10-qa``
This PR makes ``user_management`` CI like the CI for other apps. And as a by-product it gets it passing.

Do not use GIT_REFERENCE

---

appinfo/routes.php
css/setpassword.css
js/setpassword.js
js/users.js
lib/Controller/PageController.php
lib/Controller/UsersController.php
lib/Exception/InvalidUserTokenException.php
lib/Exception/UserTokenException.php
lib/Exception/UserTokenExpiredException.php
lib/Exception/UserTokenMismatchException.php
templates/main.php
templates/new_user/email-html.php
templates/new_user/resendtokenbymail.php
templates/new_user/setpassword.php
templates/new_user/tokensendnotify.php
templates/part.createuser.php
tests/acceptance/features/lib/UsersPage.php
tests/unit/ChangePasswordControllerTest.php
tests/unit/UsersControllerTest.php

Make email field as default to create user.
Previously we had username, password. With
this change it becomes username, email. This
would help admins to create users with email
address.

Make email field as default to create user

---

js/users.js

Clear email and password fields while toggling
to create user. When using password field no
trail of email should be found. Similarly when
email field is used to create user the password
field should not have previous value.

Clear email and password fields while toggling to create user

---

lib/Controller/UsersController.php
lib/Exception/InvalidUserTokenException.php
lib/Exception/UserTokenExpiredException.php
lib/Exception/UserTokenMismatchException.php

Fix the users token exception class to avoid infinite
loop when getPrevious method is called.

Fix the token exception classes to avoid infinite loop with getPrevious

---

tests/acceptance/features/webUIManageUsersGroups/addUsers.feature

This PR adds tests for checking if the sender email on password set success email is valid
Related issue: https://github.com/owncloud/enterprise/issues/2898
CI

Add tests to check from address on passwordSetSuccess

---

lib/Controller/UsersController.php
tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
tests/unit/UsersControllerTest.php

Use the global email address in the
from address when email is sent during
successful password set, by the user.
Issue #90

Fix the from address in the email when password reset

---

.drone.yml
Makefile
composer.json
composer.lock
vendor-bin/owncloud-codestyle/composer.json
vendor-bin/owncloud-codestyle/composer.lock

While investigating CI fails in user_management app (see issue #100 ) I made the ``Makefile`` targets for the various test types, so here it is.
I compared with what is in ``password_policy`` and along the way shuffled the order of some things also. So there is a little bit of extra diff in ``.drone.yml``

Add new make file targets

---

tests/acceptance/features/webUIManageUsersGroups/addUsers.feature

Fixes #107
Add tests for creating users with passwords containing special characters  such as  `!@#$%^&*()-_+=[]{}:;,.<>?~/\` , special European  characters, unicode, character with spaces etc and check the expected behaviour

webUI Acceptance tests to verify setting password with to valid and invalid values

---

js/deleteHandler.js

Delete dead code from the deleteHandler.
This was caused when the delete notifications
were replaced with confirmation dialogs.

Delete dead code from the deleteHandler

---

tests/acceptance/features/lib/DisabledUserPage.php

Old forms of the constant names were deprecated by https://github.com/owncloud/core/pull/32781/commits/db4608ace28ed62a00173021416951fb7ac3d994
Use the new forms that have underscores.

adjust acceptance test time constant names

---

tests/acceptance/features/bootstrap/WebUIUsersContext.php
tests/acceptance/features/lib/UsersPage.php

``openSettingsMenu`` is already a method in ``OwncloudPage``
and
```
class UsersPage extends OwncloudPage
```
The ``openSettingsMenu`` in ``UsersPage`` is different. It opens the "app settings menu" - the tool icon at the bottom left of a webUI page. Whereas ``openSettingsMenu`` in ``OwncloudPage`` opens the menu at the top right which has Logout and the main Settings entries.
I became aware of this because, when running webUI tests locally, I get a PHP warning:
```
PHP Warning:  Declaration of Page\UsersPage::openSettingsMenu() should be compatible with Page\OwncloudPage::openSettingsMenu(Behat\Mink\Session $session) in /home/phil/git/owncloud/core/apps-external/user_management/tests/acceptance/features/lib/UsersPage.php on line 36
PHP Stack trace:
PHP   1. {main}() …
```

Rename openSettingsMenu to openAppSettingsMenu

---

tests/acceptance/features/webUIManageUsersGroups/editUsers.feature

Some tests in encryption app are failing.
Skip those tests in encryption because those test require an extra step for encryption app to update the encryption keys.

Skip tests that are not supposed to work in encryption

---

ajax/togglegroups.php
css/style.css
js/users.js
lib/Controller/PageController.php
templates/main.php
templates/part.userlist.php
tests/acceptance/features/bootstrap/WebUIUsersContext.php
tests/acceptance/features/lib/UsersPage.php
tests/acceptance/features/webUISettingsMenu/settingsMenu.feature

Can now hide the password and quota fields using checkboxes and/or config options. Useful when configuring this screen for usage by group admins. 
Defaults to true as this is the current behaviour.

Checkboxes to hide quota and password

---

css/setpassword.css
js/setpassword.js
templates/new_user/setpassword.php
tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
tests/js/setpasswordSpec.js

Issue #147 
- implement a "retype password" field for the case when the admin creates a new user with just a username and email address. The user follows a link from the email to a UI page where they set their first password.
- adjust accceptance test steps that were changed by core PR https://github.com/owncloud/core/pull/30981

Implement "retype password" and adjust confirm password test steps

---

tests/acceptance/features/bootstrap/WebUIUsersContext.php
tests/acceptance/features/lib/UsersPage.php
tests/acceptance/features/webUIManageQuota/manageUserQuota.feature

every time the quota is changed the test used to wait for an AJAX call, but for invalid quota strings that does not happen, they are validated in JS
so in case of an invalid string we should wait for the message to appear not for the AJAX call
fixes #144

don't wait for AJAX when testing invalid quota strings

---

tests/acceptance/features/lib/UsersPage.php

need to click the select field before doing other operations
usually the test works without, but not always see #144
but actually the real user also clicks first the select-dropdown before clicking on "Other", so that test sequence is even more realistic
no failure in that setup with 10 runs of Quota tests https://drone.owncloud.com/owncloud/user_management/631

make quota tests more reliable

---

tests/acceptance/features/webUISettingsMenu/settingsMenu.feature

Related to issue https://github.com/owncloud/core/issues/34689
Sometimes elements are (sometimes) not clickable, not interactable... during `settingsMenu.feature` scenarios.
It could be related to width of the browser window and the settings on the users page making columns that go off to the right. It could also be a timing issue after clicking the bottom-left settings tool option, and then waiting until the JS has actually enabled the requested column.
I managed to get this this type of issue locally once, but can't reproduce.
Anyway, these extra tags should be on all webUI feature files:
`insulated` - behat-mink-selenium will restart the browser between each scenario - gives better isolation
`disablePreviews` - when not doing test that check for previews display, avoids the slowness of …

Add missing insulated disablePreviews tags to settingsMenu.feature

---

tests/acceptance/features/lib/UsersPage.php

There are webUI tests on the users page that adjust the settings and then check that columns are visible or not, or try to enter password or email address etc. These tests have become intermittently unreliable. I think faster test systems will see this timing issue more often.
After investigation, I realized that the settings menu on the users page opens with an animation. The observed behavior is that if the test tries to click a setting checkbox before the animation is finished, then the click is not effective, but does not return and error.
However, as soon as the test clicks to open the settings menu, `isVisible()` on the settings menu returns true - although the menu might still be animating itself.
Basically it's a PITA. We could design some sort of JS query to send in a loop to try …

Wait for settings menu animation on users page

---

appinfo/info.xml
composer.json
composer.lock

because the app is now being tested only against core `stable10` upcoming `10.2` that has dropped PHP 5.6 support.

Adjust composer files for 'drop PHP 5.6'

---

tests/acceptance/features/lib/UsersPage.php
tests/acceptance/features/webUIManageQuota/manageUserQuota.feature

`UsersPage` was falling back to the `waitTillPageIsLoaded()` method in `OwncloudPage` and that method looks for the "loading" indicator. That is not what happens on the users page.
The users page is delivered with a pre-populated lists of groups in `groupListId` - when that becomes available then the page is there, and then we can wait for any AJAX calls (e.g. the call that loads the first batch of users)
Issue https://github.com/owncloud/user_ldap/issues/386

Implement waitTillPageIsLoaded for UsersPage

---

tests/acceptance/features/lib/UsersPage.php

1) `setQuotaOfUserTo()` is responsible for attempting to set the quota of the user on the webUI. When the given quota is expected to be invalid, then it tries to wait for the "invalid" to be actioned on the webUI (so that the page will be "ready" for the next action). It looks for a notification to "pop up".
That logic is fine in general. But if the notification element does not become visible (for whatever reason) then an exception should not be thrown. At this point in the code the purpose of `waitTillXpathIsVisible()` is only to provide a reasonable wait for the page to be "ready again".
- specify just a shorter maximum wait for `notificationId` to be visible (it is a local JS thing that happens, so it does not have to wait for a round-trip AJAX to the server)
- catch the exception …

Catch waitTillXpathIsVisible() in setQuotaOfUserTo()

---

tests/acceptance/features/lib/UsersPage.php
tests/acceptance/features/webUIManageQuota/manageUserQuota.feature

After waiting for the AJAX with the users list to come in `UsersPage` `waitTillPageIsLoaded()` we know that we have some real users (at least "admin") listed on the page. But when we continue at that time to "get on with the test steps" then we often have trouble with the notification popup not happening (at least not being found).
Adding `waitForOutstandingAjaxCalls()` is a reasonable thing, but actually that returns "straight away" because the AJAX calls have finished. So that is not the complete solution.
For now, we need to get this reliable, so we also add `sleep(1)` to the end of `UsersPage` `waitTillPageIsLoaded()`. I have run the `webUIManageQuota` suite over-and-over and it passes 100% with the `sleep(1)`. Without the sleep, then this step fails a lot to find the notification: …

Wait longer in users page wait till page is loaded

---

.drone.yml
tests/acceptance/features/lib/UsersPage.php

The real problem for #167 is the failing integrity check see https://github.com/owncloud/core/issues/34787
disabling it for now
with disabled check tests pass reliably even without the waiting see #168

disable integrity check

---

tests/acceptance/features/lib/UsersPage.php

Issue https://github.com/owncloud/core/issues/34689
See the issue discussion. We know the animation timing here, and it is not worthwhile to dig into the detail of tracking the animation state with Jquery/JavaScript... So remove the ToDo and just reference the issue discussion.

Remove ToDo message about sleep

---

tests/acceptance/features/lib/UsersPage.php

Fix the function to change user's password in UserPage page object in acceptance test.
This function worked fine before but if we had wanted to do some more UI tests after this step in acceptance test, It would throw error because `waitForAjaxCallsToStartAndFinish` would never run because of the `StaleElementReference` exception.

Fix changeUserPassword function in users page page object

---

lib/Controller/UsersController.php
tests/unit/UsersControllerTest.php

Use html body for message sent via email
for password change.

Use html body for message sent via email for password change

---

tests/acceptance/features/bootstrap/WebUIUsersContext.php
tests/acceptance/features/lib/UsersPage.php
tests/acceptance/features/webUIManageUsersGroups/addGroup.feature
tests/acceptance/features/webUIManageUsersGroups/editUsers.feature

Test user count is updated (without refreshing the page) when the user is removed from or added to a group
https://github.com/owncloud/core/issues/35289
🤖

Test user count is updated when user is removed from or added to a group

---

templates/main.php

Like in the Files view I add the description to the settings icon.
The settings icon was often overlooked. I think we may prevent that with the description like in the Files app.
Manual tested
Before:
After:

Added description for the user settings section
