owncloud/user_management

.drone.yml, .gitignore, Makefile, tests/js/karma.config.js, tests/js/package.json
@PVince81 mind helping out to fix the failing tests - I don't understand this stuff - THX
```
$ node_modules/karma/bin/karma start karma.config.js --single-run
05 03 2018 22:38:22.821:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
05 03 2018 22:38:22.823:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
05 03 2018 22:38:22.828:INFO [launcher]: Starting browser PhantomJS
05 03 2018 22:38:22.989:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket HSJVz6wMWOWhPvYWAAAA with id 95311285
PhantomJS 2.1.1 (Linux 0.0.0) LOG: 'JQMIGRATE: Migrate is installed, version 1.4.0'
WARN: 'Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification'
WARN: 'Missing argument $row in OC.Notification.hide() …
```
=> Add js tests

tests/acceptance/config/behat.yml
to match core changes in https://github.com/owncloud/core/pull/30943
=> Remove /ocs/ from end of acceptance tests baseUrl

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/lib/UsersPage.php, tests/acceptance/features/webUIManageUsersGroups/addUsers.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
This is a UI test to check if the users gets deleted when an admin deletes them, and can no longer access the account.
=> UI test to delete user

README.md
Just writing some words here that might help people understand how this app applies in relation to the current state of core branches.
When there is actually a core release that has this app available with it, then a more detailed description of what the app does, installation... can be done.
=> Initial simple README

tests/js/karma.config.js, tests/js/package-lock.json, tests/js/package.json
Fixes https://github.com/owncloud/user_management/issues/29
=> Fix karma tests by upgrading libs

Makefile
This looks like a problem waiting to happen. There is code in the ajax folder, so I guess something will go wrong if it does not get in the app release?
=> Distribute ajax files

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
like done in core PR https://github.com/owncloud/core/pull/32443
=> Be consistent in acceptance test steps 'when the administrator'

tests/js/deleteHandlerSpec.js, tests/js/package-lock.json, tests/js/package.json
Update to Sinon 6.1.5 + JS test fix
=> Sinon 6 upgrade

templates/main.php
Replace add-password index with set_password.
=> Replace add-password with set_password

lib/Controller/UsersController.php, tests/unit/UsersControllerTest.php
Do not delete token if token mismatch happens.
=> Do not delete token if token mismatch happens

tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
the bug was fixed so this tests should pass now
=> unskip tests that were fixed by #64

tests/acceptance/features/bootstrap/WebUIUsersContext.php
Restore settings menu settings so that test runs doesn't change the settings.  
CI
=> Implement beforeScenario and afterScenario to restore settings to its initial state

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/lib/UsersPage.php, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
This PR adds tests for settings menu
CI
=> UI test for Settings Menu

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/webUIManageQuota/manageUserQuota.feature, tests/acceptance/features/webUIManageUsersGroups/addUsers.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
This PR changes the hardcoded passwords to user abstract one
=> change hardcoded password to use abstract password

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Rephrase statement in usersSettingsPage
Related Issue #79
=> Make enable/disable setting step clear that it is on the user management page

tests/acceptance/features/lib/UsersPage.php, tests/acceptance/features/webUIManageQuota/manageUserQuota.feature, tests/acceptance/features/webUIManageUsersGroups/addGroup.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature, tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature
Fix timing issue with web ui manageUsersQuota feature.
And fix some formatting.
Related issue: https://github.com/owncloud/user_management/issues/73
=> Ui test manage user quota fix wait problem

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Description
Rephrase then statements in usersSettingsPage
Related Issue #79
=> Rephrase then statement to be more specific

tests/acceptance/features/webUIManageQuota/manageUserQuota.feature, tests/acceptance/features/webUIManageUsersGroups/addUsers.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
1) Format feature files 
2) Use the passwords and emails the same as core in tests
=> Refactor tests 20181004

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
Forward port of: https://github.com/owncloud/core/pull/33046
Skipped because of: #24
=> Add webUI tests to disable a user as a subadmin

tests/acceptance/features/webUIManageUsersGroups/addUsers.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
Forward port of core stable10 PR https://github.com/owncloud/core/pull/33049
=> Substitute productname and edition in user management acceptance tests

tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
Invalid quota webUI acceptance tests are failing. See issue #100 
So skip the test scenario for now.
=> Skip invalid quota test - issue 100

tests/acceptance/features/webUIManageUsersGroups/addUsers.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Remove explicit user of user password on user login steps. 
Related issue: #97
CI
=> Remove explicit use of user password while user logs in

tests/acceptance/features/webUIManageQuota/manageUserQuota.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Fix acceptance test steps that were changed in core.
```
Given users have been created
``` 
to 
```
Given users have been created with default attributes
```
=> Fix steps changed in core

js/deleteHandler.js, js/groups.js, js/users.js, tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/lib/UserPageElement/GroupList.php, tests/acceptance/features/lib/UsersPage.php, tests/acceptance/features/webUIManageUsersGroups/addUsers.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature, tests/js/deleteHandlerSpec.js
Replace notification with confirm dialog for user
deletion from UI.
=> Replace notification with confirm dialog for user deletion

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/lib/UsersPage.php, tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
Fixes #128
Added webUi acceptance tests for editing user attribues such as displayname, password and group
=> Add webUI tests for editing user displayname, password and group

Makefile, phpcs.xml, tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/lib/UserPageElement/GroupList.php, tests/acceptance/features/lib/UsersPage.php, vendor-bin/php_codesniffer/composer.json
Like was merged in core in https://github.com/owncloud/core/pull/34191
So that we know if we break our own rules for acceptance test code style.
=> Add php codesniffer

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/lib/UsersPage.php, tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
Fixes #131
Add acceptance tests for removing users from the group using the webUI.
=> Add webUI tests for removing user from groups

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/lib/UsersPage.php, tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
Fixes #137 
Add webUI acceptance test for editing user email by the administrator.
=> Add webUI acceptance test for editing user email

tests/acceptance/features/webUIManageQuota/manageUserQuota.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
Issue #24 and issue #100 
Part of QA issue https://github.com/owncloud/qa/issues/601
=> Unskip and adjust tests for issues

tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
that were modified in core by PR https://github.com/owncloud/core/pull/34490
=> Adjust acceptance test steps

phpunit.xml, tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/unit/ChangePasswordControllerTest.php, tests/unit/GroupsControllerTest.php, tests/unit/MetaDataTest.php, tests/unit/PageControllerTest.php, tests/unit/UsersControllerTest.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) phpunit enable failOnRisky failOnWarning 
3) remove unused use statements
=> Phpunit 5 6

tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
Part of owncloud/core#35171
There is PR owncloud/core#35172, which will add this same changes to `stable10` and can be verified there. This will only work when that PR gets merged and tarball is created.
=> Wait for login page to appear when setting password

tests/acceptance/features/webUIManageQuota/manageUserQuota.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature, tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature, tests/acceptance/features/webUIManageUsersGroups/editUsers.feature, tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
that changed in core https://github.com/owncloud/core/pull/35438
=> Adjust create user steps

ajax/togglegroups.php
When user is successfully removed from the group
fix message that is sent by server.
=> Fix response when user is removed from group

tests/acceptance/features/webUIManageUsersGroups/addGroup.feature
We can create groups using emojis in group names .
=> Acceptance test for adding groups using emojis in group names

tests/acceptance/features/webUIAddUsers/addUsers.feature, tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
Add webui acceptance tests to:
- create delete users and using different case of the username
part of https://github.com/owncloud/core/issues/35354
=> user create and delete scenario case sensitive

tests/acceptance/features/bootstrap/WebUIUsersContext.php, tests/acceptance/features/webUIAddUsers/addUsers.feature
Test for creating users using webUI.
=> Test for creating users

.drone.yml
Currently we only run app tests against stable10 to make sure they will be compatible with the future OC core platform release.
This test guarantee that the ```user_management``` app runs correctly against the last released core version.
Part of https://github.com/owncloud/QA/issues/611
=> user management app test against latest tarball

ajax/togglegroups.php
Forward port of core `stable10` PR https://github.com/owncloud/core/pull/35769
=> fix phpstan 'Undefined variable: ' reported for togglegroups.php
